/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health check */
		get: operations['ApiV1HealthHealthCheck'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/health/live': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Liveness check */
		get: operations['ApiV1HealthLiveLivenessCheck'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/health/ready': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Readiness check */
		get: operations['ApiV1HealthReadyReadinessCheck'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/blocks': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List blocks */
		get: operations['ApiV1BlocksListBlocks'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/sessions/{session_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get session */
		get: operations['ApiV1SessionsSessionIdGetSession'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/sessions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List sessions */
		get: operations['ApiV1SessionsListSessions'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/magic-link/consume': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Consume magic link */
		get: operations['ApiV1AuthMagicLinkConsumeConsumeMagicLink'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Log out */
		post: operations['ApiV1AuthLogoutLogout'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/magic-link': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request magic link */
		post: operations['ApiV1AuthMagicLinkRequestMagicLink'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get current caregiver */
		get: operations['ApiV1MeMe'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update caregiver profile */
		patch: operations['ApiV1MeUpdateMe'];
		trace?: never;
	};
	'/api/v1/signups/{session_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Signup to session */
		post: operations['ApiV1SignupsSessionIdCreateSignup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/signups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List caregiver signups */
		get: operations['ApiV1SignupsListSignups'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/signups/{signup_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Withdraw signup */
		delete: operations['ApiV1SignupsSignupIdWithdrawSignup'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/students': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List students */
		get: operations['ApiV1StudentsListStudents'];
		put?: never;
		/** Create student */
		post: operations['ApiV1StudentsCreateStudent'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/students/{student_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get student */
		get: operations['ApiV1StudentsStudentIdGetStudent'];
		put?: never;
		post?: never;
		/** Delete student */
		delete: operations['ApiV1StudentsStudentIdDeleteStudent'];
		options?: never;
		head?: never;
		/** Update student */
		patch: operations['ApiV1StudentsStudentIdUpdateStudent'];
		trace?: never;
	};
	'/api/v1/admin/occurrences/{occurrence_id}/attendance-history': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetAttendanceHistory */
		get: operations['ApiV1AdminOccurrencesOccurrenceIdAttendanceHistoryGetAttendanceHistory'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/occurrences/{occurrence_id}/roll': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetAttendanceRoll */
		get: operations['ApiV1AdminOccurrencesOccurrenceIdRollGetAttendanceRoll'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/occurrences/{occurrence_id}/attendance': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** UpsertAttendance */
		post: operations['ApiV1AdminOccurrencesOccurrenceIdAttendanceUpsertAttendance'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/attendance/at-risk': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetAtRiskStudents */
		get: operations['ApiV1AdminSessionsSessionIdAttendanceAtRiskGetAtRiskStudents'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/attendance/stats': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetAttendanceStats */
		get: operations['ApiV1AdminSessionsSessionIdAttendanceStatsGetAttendanceStats'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/auth/google/callback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GoogleCallback */
		get: operations['ApiV1AdminAuthGoogleCallbackGoogleCallback'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/auth/google/start': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GoogleStart */
		get: operations['ApiV1AdminAuthGoogleStartGoogleStart'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logout */
		post: operations['ApiV1AdminAuthLogoutLogout'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/auth/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Me */
		get: operations['ApiV1AdminAuthMeMe'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/blocks': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List blocks */
		get: operations['ApiV1AdminBlocksListBlocks'];
		put?: never;
		/** CreateBlock */
		post: operations['ApiV1AdminBlocksCreateBlock'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/blocks/{block_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get block by ID */
		get: operations['ApiV1AdminBlocksBlockIdGetBlock'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update block */
		patch: operations['ApiV1AdminBlocksBlockIdUpdateBlock'];
		trace?: never;
	};
	'/api/v1/admin/caregivers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListCaregivers */
		get: operations['ApiV1AdminCaregiversListCaregivers'];
		put?: never;
		/** CreateCaregiver */
		post: operations['ApiV1AdminCaregiversCreateCaregiver'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/caregivers/{caregiver_id}/email': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** EmailCaregiver */
		post: operations['ApiV1AdminCaregiversCaregiverIdEmailEmailCaregiver'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/caregivers/{caregiver_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetCaregiver */
		get: operations['ApiV1AdminCaregiversCaregiverIdGetCaregiver'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** UpdateCaregiver */
		patch: operations['ApiV1AdminCaregiversCaregiverIdUpdateCaregiver'];
		trace?: never;
	};
	'/api/v1/admin/caregivers/{caregiver_id}/students': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListCaregiverStudents */
		get: operations['ApiV1AdminCaregiversCaregiverIdStudentsListCaregiverStudents'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/exclusions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List exclusions */
		get: operations['ApiV1AdminExclusionsListExclusions'];
		put?: never;
		/** CreateExclusion */
		post: operations['ApiV1AdminExclusionsCreateExclusion'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/exclusions/{exclusion_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get exclusion date by ID */
		get: operations['ApiV1AdminExclusionsExclusionIdGetExclusion'];
		put?: never;
		post?: never;
		/** Delete exclusion date */
		delete: operations['ApiV1AdminExclusionsExclusionIdDeleteExclusion'];
		options?: never;
		head?: never;
		/** Update exclusion date */
		patch: operations['ApiV1AdminExclusionsExclusionIdUpdateExclusion'];
		trace?: never;
	};
	'/api/v1/admin/locations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List locations */
		get: operations['ApiV1AdminLocationsListLocations'];
		put?: never;
		/** CreateLocation */
		post: operations['ApiV1AdminLocationsCreateLocation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/locations/{location_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get location by ID */
		get: operations['ApiV1AdminLocationsLocationIdGetLocation'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update location */
		patch: operations['ApiV1AdminLocationsLocationIdUpdateLocation'];
		trace?: never;
	};
	'/api/v1/admin/occurrences': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** CreateOccurrence */
		post: operations['ApiV1AdminOccurrencesCreateOccurrence'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/occurrences/{occurrence_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetOccurrence */
		get: operations['ApiV1AdminOccurrencesOccurrenceIdGetOccurrence'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** UpdateOccurrence */
		patch: operations['ApiV1AdminOccurrencesOccurrenceIdUpdateOccurrence'];
		trace?: never;
	};
	'/api/v1/admin/occurrences/{occurrence_id}/cancel': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** ToggleCancelOccurrence */
		patch: operations['ApiV1AdminOccurrencesOccurrenceIdCancelToggleCancelOccurrence'];
		trace?: never;
	};
	'/api/v1/admin/sessions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListSessions */
		get: operations['ApiV1AdminSessionsListSessions'];
		put?: never;
		/** CreateSession */
		post: operations['ApiV1AdminSessionsCreateSession'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/email': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** EmailSession */
		post: operations['ApiV1AdminSessionsSessionIdEmailEmailSession'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/export/attendance.csv': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ExportAttendanceCsv */
		get: operations['ApiV1AdminSessionsSessionIdExportAttendanceCsvExportAttendanceCsv'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/export/signups.csv': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ExportSignupsCsv */
		get: operations['ApiV1AdminSessionsSessionIdExportSignupsCsvExportSignupsCsv'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/occurrences': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetOccurrences */
		get: operations['ApiV1AdminSessionsSessionIdOccurrencesGetOccurrences'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetSession */
		get: operations['ApiV1AdminSessionsSessionIdGetSession'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** UpdateSession */
		patch: operations['ApiV1AdminSessionsSessionIdUpdateSession'];
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/signups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetSignups */
		get: operations['ApiV1AdminSessionsSessionIdSignupsGetSignups'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/signups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** CreateSignup */
		post: operations['ApiV1AdminSignupsCreateSignup'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/signups/{signup_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetSignup */
		get: operations['ApiV1AdminSignupsSignupIdGetSignup'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** UpdateSignup */
		patch: operations['ApiV1AdminSignupsSignupIdUpdateSignup'];
		trace?: never;
	};
	'/api/v1/admin/signups/{signup_id}/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** UpdateSignupStatus */
		patch: operations['ApiV1AdminSignupsSignupIdStatusUpdateSignupStatus'];
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/staff': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetSessionStaff */
		get: operations['ApiV1AdminSessionsSessionIdStaffGetSessionStaff'];
		put?: never;
		/** AssignStaff */
		post: operations['ApiV1AdminSessionsSessionIdStaffAssignStaff'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/staff/bulk': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** BulkAssignStaff */
		post: operations['ApiV1AdminSessionsSessionIdStaffBulkBulkAssignStaff'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/sessions/{session_id}/staff/{staff_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** RemoveStaff */
		delete: operations['ApiV1AdminSessionsSessionIdStaffStaffIdRemoveStaff'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/staff': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListStaff */
		get: operations['ApiV1AdminStaffListStaff'];
		put?: never;
		/** CreateStaff */
		post: operations['ApiV1AdminStaffCreateStaff'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/staff/{staff_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetStaff */
		get: operations['ApiV1AdminStaffStaffIdGetStaff'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** UpdateStaff */
		patch: operations['ApiV1AdminStaffStaffIdUpdateStaff'];
		trace?: never;
	};
	'/api/v1/admin/staff/availability': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetStaffAvailability */
		get: operations['ApiV1AdminStaffAvailabilityGetStaffAvailability'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/staff/{staff_id}/sessions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetStaffSessions */
		get: operations['ApiV1AdminStaffStaffIdSessionsGetStaffSessions'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/students': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** ListStudents */
		get: operations['ApiV1AdminStudentsListStudents'];
		put?: never;
		/** CreateStudent */
		post: operations['ApiV1AdminStudentsCreateStudent'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/students/{student_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetStudent */
		get: operations['ApiV1AdminStudentsStudentIdGetStudent'];
		put?: never;
		post?: never;
		/** DeleteStudent */
		delete: operations['ApiV1AdminStudentsStudentIdDeleteStudent'];
		options?: never;
		head?: never;
		/** UpdateStudent */
		patch: operations['ApiV1AdminStudentsStudentIdUpdateStudent'];
		trace?: never;
	};
	'/api/v1/admin/students/{student_id}/signups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** GetStudentSignups */
		get: operations['ApiV1AdminStudentsStudentIdSignupsGetStudentSignups'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AttendanceRecord */
		AttendanceRecord: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			occurrence_id: string;
			/** Format: uuid */
			student_id: string;
			/** @enum {string} */
			status: 'present' | 'absent_known' | 'absent_unknown';
			reason?: string | null;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
		/** AttendanceRoll */
		AttendanceRoll: {
			/** Format: uuid */
			occurrence_id: string;
			/** Format: uuid */
			session_id: string;
			/** Format: date-time */
			starts_at: string;
			/** Format: date-time */
			ends_at: string;
			cancelled: boolean;
			items: components['schemas']['AttendanceRollItem'][];
		};
		/** AttendanceRollItem */
		AttendanceRollItem: {
			/** Format: uuid */
			signup_id: string;
			/** Format: uuid */
			student_id: string;
			student_name: string;
			caregiver_name: string;
			attendance?: components['schemas']['AttendanceRecord'] | null;
		};
		/** AttendanceStats */
		AttendanceStats: {
			/** Format: uuid */
			session_id: string;
			total_occurrences: number;
			total_students: number;
			average_attendance_rate: number;
			students_with_perfect_attendance: number;
			students_with_good_attendance: number;
			students_with_poor_attendance: number;
			best_attended_occurrence: unknown;
			worst_attended_occurrence: unknown;
		};
		/** AttendanceUpsert */
		AttendanceUpsert: {
			/** Format: uuid */
			studentId: string;
			/** @enum {string} */
			status: 'present' | 'absent_known' | 'absent_unknown';
			reason?: string | null;
		};
		/** BlockCreate */
		BlockCreate: {
			year: number;
			name: string;
			blockType: string;
			/** Format: date */
			startDate: string;
			/** Format: date */
			endDate: string;
		};
		/** BlockOccurrences */
		BlockOccurrences: {
			/** Format: uuid */
			block_id: string;
			block_name: string;
			block_type: string;
			occurrences: components['schemas']['public_schemas_occurrence_Occurrence'][];
		};
		/** BlockUpdate */
		BlockUpdate: {
			startDate?: string | null;
			endDate?: string | null;
			year?: number | null;
			name?: string | null;
			blockType?: string | null;
		};
		/** BulkStaffAssignment */
		BulkStaffAssignment: {
			staffIds: string[];
			/** @default false */
			replace: boolean;
		};
		/** Caregiver */
		Caregiver: {
			/** Format: uuid */
			id: string;
			email: string;
			name?: string | null;
			phone?: string | null;
			email_verified: boolean;
			/** @default false */
			profile_complete: boolean;
			referral_source?: string | null;
			/** @default [] */
			students: components['schemas']['StudentBase'][];
		};
		/** CaregiverCreate */
		CaregiverCreate: {
			email: string;
			name?: string | null;
			phone?: string | null;
			/** @default false */
			emailVerified: boolean;
			referralSource?: string | null;
			/** @default false */
			subscribeNewsletter: boolean;
		};
		/** CaregiverMe */
		CaregiverMe: {
			/** Format: uuid */
			id: string;
			email: string;
			name?: string | null;
			phone?: string | null;
			/** @default false */
			email_verified: boolean;
			/** @default false */
			profile_complete: boolean;
		};
		/** CaregiverMessage */
		CaregiverMessage: {
			subject: string;
			message: string;
		};
		/** ExclusionDate */
		ExclusionDate: {
			/** Format: uuid */
			id: string;
			year: number;
			/** Format: date */
			date: string;
			reason?: string | null;
		};
		/** ExclusionDateCreate */
		ExclusionDateCreate: {
			year: number;
			/** Format: date */
			date: string;
			reason?: string | null;
		};
		/** ExclusionDateUpdate */
		ExclusionDateUpdate: {
			year?: number | null;
			date?: string | null;
			reason?: string | null;
		};
		/** HealthCheckResponse */
		HealthCheckResponse: {
			/** @description Health status of the application */
			status: boolean;
			/** @description Timestamp of the health check */
			timestamp: string;
			/** @description Version of the application */
			version: string;
			/** @description Name of the service */
			service: string;
			/** @description Debug mode status */
			debug: boolean;
		};
		/** LivenessCheckResponse */
		LivenessCheckResponse: {
			/** @description Liveness status of the application */
			alive: boolean;
			/** @description Timestamp of the liveness check */
			timestamp: string;
		};
		/** LocationCreate */
		LocationCreate: {
			name: string;
			address: string;
			region: string;
			lat: number;
			lng: number;
			instructions?: string | null;
			contactName: string;
			/** Format: email */
			contactEmail: string;
			contactPhone?: string | null;
			internalNotes?: string | null;
		};
		/** LocationUpdate */
		LocationUpdate: {
			name?: string | null;
			address?: string | null;
			region?: string | null;
			lat?: number | null;
			lng?: number | null;
			instructions?: string | null;
			contactName?: string | null;
			contactEmail?: string | null;
			contactPhone?: string | null;
			internalNotes?: string | null;
		};
		/** MagicLinkRequest */
		MagicLinkRequest: {
			/** Format: email */
			email: string;
			returnTo?: string | null;
		};
		/** MagicLinkRequestResponse */
		MagicLinkRequestResponse: {
			/** @default true */
			ok: boolean;
			debug_token?: string | null;
		};
		/** OccurrenceCreate */
		OccurrenceCreate: {
			/** Format: date-time */
			startsAt: string;
			/** Format: date-time */
			endsAt: string;
			/** Format: uuid */
			sessionId: string;
			/** Format: uuid */
			blockId: string;
		};
		/** OccurrenceUpdate */
		OccurrenceUpdate: {
			startsAt?: string | null;
			endsAt?: string | null;
			cancelled?: boolean | null;
			cancellationReason?: string | null;
		};
		/** ReadinessCheckResponse */
		ReadinessCheckResponse: {
			/** @description Readiness status of the application */
			ready: boolean;
			/** @description Timestamp of the readiness check */
			timestamp: string;
		};
		/** SessionCreate */
		SessionCreate: {
			year: number;
			/** @enum {string} */
			sessionType: 'term' | 'special' | 'event';
			name: string;
			ageLower: number;
			ageUpper: number;
			/** Format: duration */
			startTime: string;
			/** Format: duration */
			endTime: string;
			dayOfWeek: number;
			capacity: number;
			photoAlbumUrl?: string | null;
			internalNotes?: string | null;
			/** @default false */
			archived: boolean;
			/** Format: uuid */
			locationId: string;
			blocks: string[];
		};
		/** SessionDetail */
		SessionDetail: {
			/** Format: uuid */
			id: string;
			name: string;
			year: number;
			age_lower: number;
			age_upper: number;
			day_of_week?: number | null;
			/** Format: duration */
			start_time: string;
			/** Format: duration */
			end_time: string;
			/** @default [] */
			blocks: string[];
			location: components['schemas']['public_schemas_session_Location'];
			/** @default [] */
			occurrences: components['schemas']['public_schemas_occurrence_Occurrence'][];
			/** @default [] */
			occurrences_by_block: components['schemas']['BlockOccurrences'][];
		};
		/** SessionEmail */
		SessionEmail: {
			title: string;
			body: string;
		};
		/** SessionStaffAssignment */
		SessionStaffAssignment: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			staff_id: string;
			/** Format: uuid */
			session_id: string;
			/** Format: date-time */
			assigned_at: string;
		};
		/** SessionUpdate */
		SessionUpdate: {
			year?: number | null;
			/** @enum {null|string} */
			sessionType?: 'term' | 'special' | 'event' | null;
			name?: string | null;
			ageLower?: number | null;
			ageUpper?: number | null;
			startTime?: string | null;
			endTime?: string | null;
			dayOfWeek?: number | null;
			capacity?: number | null;
			photoAlbumUrl?: string | null;
			internalNotes?: string | null;
			archived?: boolean | null;
			locationId?: string | null;
		};
		/** Signup */
		Signup: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			student_id: string;
			/** Format: uuid */
			session_id: string;
			status: components['schemas']['SignupStatus'];
			withdrawn_at?: string | null;
			pickup_dropoff?: string | null;
			created_at?: string | null;
			/** @default false */
			needs_devices: boolean;
			student_name?: string | null;
			guardian_name?: string | null;
			email?: string | null;
			phone?: string | null;
			date_of_birth?: string | null;
			media_consent?: boolean | null;
		};
		/** SignupCreate */
		SignupCreate: {
			status?: components['schemas']['SignupStatus'];
			pickupDropoff?: string | null;
			/** Format: uuid */
			studentId: string;
			/** Format: uuid */
			sessionId: string;
		};
		/** SignupCreateRequest */
		SignupCreateRequest: {
			studentId: string;
			pickupDropoff?: string | null;
			/** @default false */
			needsDevices: boolean;
		};
		/** SignupCreateResponse */
		SignupCreateResponse: {
			id: string;
			/** @enum {string} */
			status: 'pending' | 'confirmed' | 'waitlisted' | 'withdrawn';
		};
		/** SignupFull */
		SignupFull: {
			/** Format: uuid */
			id: string;
			/** @enum {string} */
			status: 'pending' | 'confirmed' | 'waitlisted' | 'withdrawn';
			/** Format: date-time */
			created_at: string;
			withdrawn_at?: string | null;
			pickup_dropoff?: string | null;
			/** @default false */
			needs_devices: boolean;
			/** Format: uuid */
			session_id: string;
			session_name: string;
			/** Format: uuid */
			student_id: string;
			student_name: string;
		};
		/**
		 * SignupStatus
		 * @default waitlisted
		 * @enum {string}
		 */
		SignupStatus: 'pending' | 'confirmed' | 'waitlisted' | 'withdrawn';
		/** SignupStatusUpdate */
		SignupStatusUpdate: {
			status: components['schemas']['SignupStatus'];
			reason?: string | null;
			/** @default false */
			notifyCaregiver: boolean;
		};
		/** SignupStudent */
		SignupStudent: {
			/** Format: uuid */
			id: string;
			/** Format: uuid */
			student_id: string;
			/** Format: uuid */
			session_id: string;
			status: components['schemas']['SignupStatus'];
			withdrawn_at?: string | null;
			pickup_dropoff?: string | null;
			created_at?: string | null;
			/** @default false */
			needs_devices: boolean;
			student_name?: string | null;
			guardian_name?: string | null;
			email?: string | null;
			phone?: string | null;
			date_of_birth?: string | null;
			media_consent?: boolean | null;
			student: components['schemas']['StudentBase'];
		};
		/** SignupUpdate */
		SignupUpdate: {
			status?: components['schemas']['SignupStatus'] | null;
			pickupDropoff?: string | null;
		};
		/** Staff */
		Staff: {
			/** Format: uuid */
			id: string;
			name: string;
			/** Format: email */
			email: string;
			sso_id: string;
			active: boolean;
			last_login_at?: string | null;
			deactivated_at?: string | null;
		};
		/** StaffAvailability */
		StaffAvailability: {
			/** Format: uuid */
			staff_id: string;
			name: string;
			/** Format: email */
			email: string;
			active: boolean;
			assigned_session_count: number;
			session_ids: string[];
		};
		/** StaffCreate */
		StaffCreate: {
			name: string;
			/** Format: email */
			email: string;
			ssoId: string;
		};
		/** StaffPublic */
		StaffPublic: {
			/** Format: uuid */
			id: string;
			name: string;
			/** Format: email */
			email: string;
			active: boolean;
			last_login_at?: string | null;
		};
		/** StaffSessionSummary */
		StaffSessionSummary: {
			/** Format: uuid */
			id: string;
			name: string;
			year: number;
			session_type: string;
		};
		/** StaffUpdate */
		StaffUpdate: {
			name?: string | null;
			email?: string | null;
			active?: boolean | null;
		};
		/** StudentAttendanceSummary */
		StudentAttendanceSummary: {
			/** Format: uuid */
			student_id: string;
			student_name: string;
			total_occurrences: number;
			present_count: number;
			absent_known_count: number;
			absent_unknown_count: number;
			attendance_rate: number;
			is_at_risk: boolean;
		};
		/** StudentBase */
		StudentBase: {
			/** Format: uuid */
			id: string;
			name?: string | null;
			date_of_birth?: string | null;
			media_consent?: boolean | null;
			medical_info?: string | null;
			other_info?: string | null;
			/** @default false */
			archived: boolean;
		};
		/** Block */
		admin_schemas_block_Block: {
			/** Format: uuid */
			id: string;
			year: number;
			name: string;
			block_type: string;
			/** Format: date */
			start_date: string;
			/** Format: date */
			end_date: string;
		};
		/** CaregiverUpdate */
		admin_schemas_caregiver_CaregiverUpdate: {
			name?: string | null;
			email?: string | null;
			phone?: string | null;
		};
		/** Location */
		admin_schemas_location_Location: {
			/** Format: uuid */
			id: string;
			name: string;
			address: string;
			region: string;
			lat: number;
			lng: number;
			instructions?: string | null;
			contact_name: string;
			/** Format: email */
			contact_email: string;
			contact_phone?: string | null;
			internal_notes?: string | null;
		};
		/** Occurrence */
		admin_schemas_occurrence_Occurrence: {
			/** Format: uuid */
			id: string;
			/** Format: date-time */
			starts_at: string;
			/** Format: date-time */
			ends_at: string;
			cancelled: boolean;
			/** Format: uuid */
			block_id: string;
			/** Format: uuid */
			session_id: string;
			cancellation_reason?: string | null;
		};
		/** Student */
		admin_schemas_student_Student: {
			/** Format: uuid */
			id: string;
			name?: string | null;
			date_of_birth?: string | null;
			media_consent?: boolean | null;
			medical_info?: string | null;
			other_info?: string | null;
			/** @default false */
			archived: boolean;
			caregiver: components['schemas']['Caregiver'];
		};
		/** StudentCreate */
		admin_schemas_student_StudentCreate: {
			/** Format: uuid */
			caregiverId: string;
			name: string;
			/** Format: date */
			dateOfBirth: string;
			mediaConsent: boolean;
			medicalInfo?: string | null;
			otherInfo?: string | null;
			region?: string | null;
			ethnicity?: string | null;
			schoolName?: string | null;
			gender?: string | null;
		};
		/** StudentUpdate */
		admin_schemas_student_StudentUpdate: {
			name?: string | null;
			dateOfBirth?: string | null;
			mediaConsent?: boolean | null;
			medicalInfo?: string | null;
			otherInfo?: string | null;
			archived?: boolean | null;
		};
		/** CaregiverUpdate */
		caregiver_schemas_caregiver_CaregiverUpdate: {
			name?: string | null;
			phone?: string | null;
			/** @default false */
			subscribeNewsletter: boolean;
			referralSource?: string | null;
		};
		/** Student */
		caregiver_schemas_student_Student: {
			/** Format: uuid */
			id: string;
			name: string;
			/** Format: date */
			date_of_birth: string;
			media_consent: boolean;
			medical_info?: string | null;
			/** @default false */
			needs_devices: boolean;
			other_info?: string | null;
			/** @default false */
			archived: boolean;
		};
		/** StudentCreate */
		caregiver_schemas_student_StudentCreate: {
			name: string;
			/** Format: date */
			dateOfBirth: string;
			/** @default false */
			mediaConsent: boolean;
			medicalInfo?: string | null;
			/** @default false */
			needsDevices: boolean;
			otherInfo?: string | null;
			region?: string | null;
			ethnicity?: string | null;
			schoolName?: string | null;
		};
		/** StudentUpdate */
		caregiver_schemas_student_StudentUpdate: {
			name?: string | null;
			dateOfBirth?: string | null;
			mediaConsent?: boolean | null;
			medicalInfo?: string | null;
			otherInfo?: string | null;
			archived?: boolean | null;
			region?: string | null;
			ethnicity?: string | null;
			schoolName?: string | null;
			gender?: string | null;
		};
		/** Block */
		public_schemas_block_Block: {
			/** Format: uuid */
			id: string;
			year: number;
			name: string;
			/** Format: date */
			start_date: string;
			/** Format: date */
			end_date: string;
			block_type: string;
		};
		/** Occurrence */
		public_schemas_occurrence_Occurrence: {
			/** Format: date-time */
			starts_at: string;
			/** Format: date-time */
			ends_at: string;
			cancelled: boolean;
			/** Format: uuid */
			block_id: string;
			/** Format: uuid */
			session_id: string;
			cancellation_reason?: string | null;
		};
		/** Location */
		public_schemas_session_Location: {
			name: string;
			address: string;
			region: string;
			lat: number;
			lng: number;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	ApiV1HealthHealthCheck: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthCheckResponse'];
				};
			};
		};
	};
	ApiV1HealthLiveLivenessCheck: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LivenessCheckResponse'];
				};
			};
		};
	};
	ApiV1HealthReadyReadinessCheck: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ReadinessCheckResponse'];
				};
			};
		};
	};
	ApiV1BlocksListBlocks: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['public_schemas_block_Block'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
		};
	};
	ApiV1SessionsSessionIdGetSession: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SessionDetail'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1SessionsListSessions: {
		parameters: {
			query?: {
				limit?: number | null;
				offset?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: unknown[];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AuthMagicLinkConsumeConsumeMagicLink: {
		parameters: {
			query: {
				token: string;
				returnTo?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AuthLogoutLogout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
		};
	};
	ApiV1AuthMagicLinkRequestMagicLink: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['MagicLinkRequest'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MagicLinkRequestResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1MeMe: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CaregiverMe'];
				};
			};
		};
	};
	ApiV1MeUpdateMe: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['caregiver_schemas_caregiver_CaregiverUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CaregiverMe'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1SignupsSessionIdCreateSignup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SignupCreateRequest'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SignupCreateResponse'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1SignupsListSignups: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SignupFull'][];
				};
			};
		};
	};
	ApiV1SignupsSignupIdWithdrawSignup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				signup_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1StudentsListStudents: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['caregiver_schemas_student_Student'][];
				};
			};
		};
	};
	ApiV1StudentsCreateStudent: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['caregiver_schemas_student_StudentCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['caregiver_schemas_student_Student'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1StudentsStudentIdGetStudent: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				student_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['caregiver_schemas_student_Student'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1StudentsStudentIdDeleteStudent: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				student_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1StudentsStudentIdUpdateStudent: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				student_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['caregiver_schemas_student_StudentUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['caregiver_schemas_student_Student'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminOccurrencesOccurrenceIdAttendanceHistoryGetAttendanceHistory: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				occurrence_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AttendanceRecord'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminOccurrencesOccurrenceIdRollGetAttendanceRoll: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				occurrence_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AttendanceRoll'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminOccurrencesOccurrenceIdAttendanceUpsertAttendance: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				occurrence_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AttendanceUpsert'][];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AttendanceRecord'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdAttendanceAtRiskGetAtRiskStudents: {
		parameters: {
			query?: {
				threshold?: number;
			};
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StudentAttendanceSummary'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdAttendanceStatsGetAttendanceStats: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AttendanceStats'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminAuthGoogleCallbackGoogleCallback: {
		parameters: {
			query?: {
				code?: string | null;
				error?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminAuthGoogleStartGoogleStart: {
		parameters: {
			query?: {
				returnTo?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminAuthLogoutLogout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
		};
	};
	ApiV1AdminAuthMeMe: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: unknown;
					};
				};
			};
		};
	};
	ApiV1AdminBlocksListBlocks: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['admin_schemas_block_Block'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
		};
	};
	ApiV1AdminBlocksCreateBlock: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BlockCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_block_Block'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminBlocksBlockIdGetBlock: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				block_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_block_Block'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminBlocksBlockIdUpdateBlock: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				block_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BlockUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_block_Block'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminCaregiversListCaregivers: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['Caregiver'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
		};
	};
	ApiV1AdminCaregiversCreateCaregiver: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CaregiverCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Caregiver'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminCaregiversCaregiverIdEmailEmailCaregiver: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				caregiver_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CaregiverMessage'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminCaregiversCaregiverIdGetCaregiver: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				caregiver_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Caregiver'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminCaregiversCaregiverIdUpdateCaregiver: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				caregiver_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['admin_schemas_caregiver_CaregiverUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Caregiver'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminCaregiversCaregiverIdStudentsListCaregiverStudents: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				caregiver_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['admin_schemas_student_Student'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminExclusionsListExclusions: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['ExclusionDate'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
		};
	};
	ApiV1AdminExclusionsCreateExclusion: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ExclusionDateCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ExclusionDate'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminExclusionsExclusionIdGetExclusion: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				exclusion_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ExclusionDate'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminExclusionsExclusionIdDeleteExclusion: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				exclusion_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminExclusionsExclusionIdUpdateExclusion: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				exclusion_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ExclusionDateUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ExclusionDate'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminLocationsListLocations: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['admin_schemas_location_Location'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
		};
	};
	ApiV1AdminLocationsCreateLocation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LocationCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_location_Location'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminLocationsLocationIdGetLocation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_location_Location'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminLocationsLocationIdUpdateLocation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LocationUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_location_Location'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminOccurrencesCreateOccurrence: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['OccurrenceCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_occurrence_Occurrence'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminOccurrencesOccurrenceIdGetOccurrence: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				occurrence_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_occurrence_Occurrence'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminOccurrencesOccurrenceIdUpdateOccurrence: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				occurrence_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['OccurrenceUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_occurrence_Occurrence'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminOccurrencesOccurrenceIdCancelToggleCancelOccurrence: {
		parameters: {
			query?: {
				cancelled?: boolean;
				cancellation_reason?: string | null;
			};
			header?: never;
			path: {
				occurrence_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_occurrence_Occurrence'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsListSessions: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: unknown[];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
		};
	};
	ApiV1AdminSessionsCreateSession: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SessionCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdEmailEmailSession: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SessionEmail'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdExportAttendanceCsvExportAttendanceCsv: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Stream Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdExportSignupsCsvExportSignupsCsv: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Stream Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdOccurrencesGetOccurrences: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['admin_schemas_occurrence_Occurrence'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdGetSession: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdUpdateSession: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SessionUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdSignupsGetSignups: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['Signup'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSignupsCreateSignup: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SignupCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Signup'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSignupsSignupIdGetSignup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				signup_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SignupStudent'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSignupsSignupIdUpdateSignup: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				signup_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SignupUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SignupStudent'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSignupsSignupIdStatusUpdateSignupStatus: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				signup_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SignupStatusUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SignupStudent'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdStaffGetSessionStaff: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StaffPublic'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdStaffAssignStaff: {
		parameters: {
			query: {
				staff_id: string;
			};
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SessionStaffAssignment'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdStaffBulkBulkAssignStaff: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['BulkStaffAssignment'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SessionStaffAssignment'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminSessionsSessionIdStaffStaffIdRemoveStaff: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
				staff_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStaffListStaff: {
		parameters: {
			query?: {
				active_only?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StaffPublic'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStaffCreateStaff: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['StaffCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Staff'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStaffStaffIdGetStaff: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				staff_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Staff'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStaffStaffIdUpdateStaff: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				staff_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['StaffUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Staff'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStaffAvailabilityGetStaffAvailability: {
		parameters: {
			query?: {
				year?: number | null;
				active_only?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StaffAvailability'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStaffStaffIdSessionsGetStaffSessions: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				staff_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StaffSessionSummary'][];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStudentsListStudents: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['admin_schemas_student_Student'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
		};
	};
	ApiV1AdminStudentsCreateStudent: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['admin_schemas_student_StudentCreate'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_student_Student'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStudentsStudentIdGetStudent: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				student_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_student_Student'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStudentsStudentIdDeleteStudent: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				student_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStudentsStudentIdUpdateStudent: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				student_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['admin_schemas_student_StudentUpdate'];
			};
		};
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['admin_schemas_student_Student'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ApiV1AdminStudentsStudentIdSignupsGetStudentSignups: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				student_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						items?: components['schemas']['Signup'][];
						/** @description Maximal number of items to send. */
						limit?: number;
						/** @description Offset from the beginning of the query. */
						offset?: number;
						/** @description Total number of items. */
						total?: number;
					};
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
}
