"""add_cascade_delete_for_caregivers_students_signups

Revision ID: 021059cf9312
Revises: 2bc2e459ef46
Create Date: 2026-02-09 14:39:48.587477

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '021059cf9312'
down_revision = '2bc2e459ef46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('signups_session_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_signups_student_id_students'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_signups_session_id_sessions'), 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_signups_student_id_students'), 'students', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('children_caregiver_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_students_caregiver_id_caregivers'), 'caregivers', ['caregiver_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_caregiver_id_caregivers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('children_caregiver_id_fkey'), 'caregivers', ['caregiver_id'], ['id'])

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_signups_student_id_students'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_signups_session_id_sessions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_signups_student_id_students'), 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('signups_session_id_fkey'), 'sessions', ['session_id'], ['id'])

    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
